using Pkg
Pkg.add("Plots")
Pkg.add("LaTeXStrings")
Pkg.add("ControlSystems")
Pkg.add("JLD2")
Pkg.add("Zygote")
Pkg.add("Distributions")
Pkg.add("ControlSystemIdentification")
Pkg.add("ControlSystemsBase")
Pkg.add("JSON3")
Pkg.add("StatsPlots")
Pkg.add("JSON")
Pkg.add("MatrixEquations")
Pkg.add("Optim")